### ISSUE TITLE
Can't scroll tags list on desktop

### ISSUE THREAD

**Issue by wilt00** [evadecker/genderswap.fm#303]
On mobile, you can scroll the list of tags below the search bar by tapping and sliding. On desktop however, if the tags extend off the edge of the screen, there is no way to scroll them - neither clicking and dragging nor using the scroll wheel with the pointer over the tag bar work. (I would submit a PR, maybe using something like `@media (pointer: fine)`, but I'm not sure how to set up supabase locally for testing)

Tested in Firefox 132.0.2 and Chrome 131.0.6778.70 on Windows 11

**Comment by evadecker** [comment]
Thanks for reporting this! Should be an easy fix. Works for me on desktop with a trackpad but I neglected to test with other input devices.

If you want to pull and submit a PR, you should be able to run the app even without connecting to Supabase, I think? If not, will update soon :)

**Comment by evadecker** [comment]
@wilt00 Can you check [this deploy preview](https://deploy-preview-304--genderswap.netlify.app/) and confirm it fixes the issue? I don't have a Windows device to test on.

**Comment by wilt00** [comment]
Looks great, thank you! 
![scroll](https://github.com/user-attachments/assets/37c322b8-bfa4-4c4e-a2e7-6574e641d92b)
